-- LoveLink Dating App Database Initialization
-- Run this script to create the database

-- Create database
CREATE DATABASE IF NOT EXISTS lovelink
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE lovelink;

-- Note: The tables will be automatically created by TypeORM's synchronize feature
-- when the application starts. The schema below is for reference only.

-- Users Table (auto-generated by TypeORM)
-- CREATE TABLE users (
--   id VARCHAR(36) PRIMARY KEY,
--   email VARCHAR(255) NOT NULL UNIQUE,
--   password VARCHAR(255) NOT NULL,
--   isActive BOOLEAN DEFAULT TRUE,
--   lastActive DATETIME,
--   createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
--   updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
-- );

-- Profiles Table (auto-generated by TypeORM)
-- CREATE TABLE profiles (
--   id VARCHAR(36) PRIMARY KEY,
--   name VARCHAR(50) NOT NULL,
--   age INT NOT NULL,
--   bio TEXT,
--   profilePhoto VARCHAR(255),
--   gender ENUM('male', 'female', 'other') DEFAULT 'other',
--   interestedIn ENUM('male', 'female', 'other'),
--   location VARCHAR(255),
--   latitude DECIMAL(10, 8),
--   longitude DECIMAL(11, 8),
--   maxDistance INT DEFAULT 50,
--   minAgePreference INT DEFAULT 18,
--   maxAgePreference INT DEFAULT 100,
--   userId VARCHAR(36) NOT NULL UNIQUE,
--   createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
--   updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
--   FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
-- );

-- Swipes Table (auto-generated by TypeORM)
-- CREATE TABLE swipes (
--   id VARCHAR(36) PRIMARY KEY,
--   swiperId VARCHAR(36) NOT NULL,
--   swipedId VARCHAR(36) NOT NULL,
--   direction ENUM('left', 'right') NOT NULL,
--   createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
--   UNIQUE KEY unique_swipe (swiperId, swipedId),
--   FOREIGN KEY (swiperId) REFERENCES users(id) ON DELETE CASCADE,
--   FOREIGN KEY (swipedId) REFERENCES users(id) ON DELETE CASCADE
-- );

-- Matches Table (auto-generated by TypeORM)
-- CREATE TABLE matches (
--   id VARCHAR(36) PRIMARY KEY,
--   user1Id VARCHAR(36) NOT NULL,
--   user2Id VARCHAR(36) NOT NULL,
--   isActive BOOLEAN DEFAULT TRUE,
--   matchedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
--   unmatchedAt DATETIME,
--   FOREIGN KEY (user1Id) REFERENCES users(id) ON DELETE CASCADE,
--   FOREIGN KEY (user2Id) REFERENCES users(id) ON DELETE CASCADE
-- );

-- Messages Table (auto-generated by TypeORM)
-- CREATE TABLE messages (
--   id VARCHAR(36) PRIMARY KEY,
--   matchId VARCHAR(36) NOT NULL,
--   senderId VARCHAR(36) NOT NULL,
--   content TEXT NOT NULL,
--   isRead BOOLEAN DEFAULT FALSE,
--   sentAt DATETIME DEFAULT CURRENT_TIMESTAMP,
--   FOREIGN KEY (matchId) REFERENCES matches(id) ON DELETE CASCADE,
--   FOREIGN KEY (senderId) REFERENCES users(id) ON DELETE CASCADE
-- );

-- Indexes for better performance
-- CREATE INDEX idx_profiles_gender ON profiles(gender);
-- CREATE INDEX idx_profiles_age ON profiles(age);
-- CREATE INDEX idx_swipes_swiper ON swipes(swiperId);
-- CREATE INDEX idx_swipes_swiped ON swipes(swipedId);
-- CREATE INDEX idx_matches_user1 ON matches(user1Id);
-- CREATE INDEX idx_matches_user2 ON matches(user2Id);
-- CREATE INDEX idx_messages_match ON messages(matchId);
-- CREATE INDEX idx_messages_sender ON messages(senderId);

SELECT 'Database lovelink created successfully!' AS status;

